# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(582, 697)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 10, 231, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(350, 40, 211, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 541, 41))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 39))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_2.setObjectName("label_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 160, 541, 121))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 539, 119))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.har_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.har_1.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.har_1.setObjectName("har_1")
        self.har_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.har_2.setGeometry(QtCore.QRect(10, 50, 141, 17))
        self.har_2.setObjectName("har_2")
        self.har_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.har_3.setGeometry(QtCore.QRect(10, 70, 121, 17))
        self.har_3.setObjectName("har_3")
        self.har_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.har_4.setGeometry(QtCore.QRect(10, 90, 121, 17))
        self.har_4.setObjectName("har_4")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit.setGeometry(QtCore.QRect(310, 30, 221, 81))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setGeometry(QtCore.QRect(310, 10, 47, 13))
        self.label_5.setObjectName("label_5")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_4.setObjectName("label_4")
        self.scrollArea_4 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_4.setGeometry(QtCore.QRect(20, 310, 171, 101))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 169, 99))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.pl_1 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.pl_1.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.pl_1.setObjectName("pl_1")
        self.pl_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.pl_2.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.pl_2.setObjectName("pl_2")
        self.pl_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_4)
        self.pl_3.setGeometry(QtCore.QRect(10, 70, 82, 17))
        self.pl_3.setObjectName("pl_3")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(19, 429, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.scrollArea_5 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_5.setGeometry(QtCore.QRect(280, 430, 31, 21))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 29, 19))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 660, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 540, 101, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 540, 101, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(460, 540, 101, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(230, 310, 331, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 570, 101, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 570, 101, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(460, 570, 101, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 570, 221, 21))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(280, 430, 31, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(160, 470, 91, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 470, 61, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 470, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 500, 61, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(160, 500, 91, 16))
        self.label_11.setObjectName("label_11")
        self.scrollArea_6 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_6.setGeometry(QtCore.QRect(20, 470, 131, 61))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 129, 59))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.radioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.radioButton.setGeometry(QtCore.QRect(10, 0, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 600, 581, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 620, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(240, 620, 101, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(350, 630, 47, 13))
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 581, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выбор объекта аналога"))
        self.label.setText(_translate("Dialog", "Нормативная база"))
        self.lineEdit.setText(_translate("Dialog", "СНиП 1.04.03-85*"))
        self.comboBox.setCurrentText(_translate("Dialog", "Жилые здания "))
        self.comboBox.setItemText(0, _translate("Dialog", "Жилые здания "))
        self.comboBox.setItemText(1, _translate("Dialog", "Здание 1 этажное"))
        self.comboBox.setItemText(2, _translate("Dialog", "Здание 2 этажное "))
        self.comboBox.setItemText(3, _translate("Dialog", "Здание 3 этажное"))
        self.comboBox.setItemText(4, _translate("Dialog", "Здание 4 этажное"))
        self.comboBox.setItemText(5, _translate("Dialog", "Здание 5 этажное"))
        self.comboBox.setItemText(6, _translate("Dialog", "Здание 9 этажное"))
        self.comboBox.setItemText(7, _translate("Dialog", "Здание 10 этажное"))
        self.comboBox.setItemText(8, _translate("Dialog", "Здание 12 этажное"))
        self.comboBox.setItemText(9, _translate("Dialog", "Здание 14 этажное"))
        self.comboBox.setItemText(10, _translate("Dialog", "Здание 16 этажное"))
        self.comboBox.setItemText(11, _translate("Dialog", "Здание 22 этажное"))
        self.comboBox_2.setCurrentText(_translate("Dialog", "Торговля и общественное питание "))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Торговля и общественное питание "))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Универсам"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Гастроном"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Магазин специализированный"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Хлеб кондитерский "))
        self.comboBox_2.setItemText(5, _translate("Dialog", "Магазин заказов"))
        self.label_3.setText(_translate("Dialog", ""))
        self.label_2.setText(_translate("Dialog", "Объект "))
        self.har_1.setText(_translate("Dialog", "Крупнопанельное"))
        self.har_2.setText(_translate("Dialog", "Каркасно-панельное"))
        self.har_3.setText(_translate("Dialog", "Объемно-блочное"))
        self.har_4.setText(_translate("Dialog", "Монолитное"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Крупнопанельное </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Каркасно-панельное </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Объемно-блочное </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Монолитное</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Выбраны:"))
        self.label_4.setText(_translate("Dialog", "Характеристика"))
        self.pl_1.setText(_translate("Dialog", "6 000"))
        self.pl_2.setText(_translate("Dialog", "12 000"))
        self.pl_3.setText(_translate("Dialog", "18 000"))
        self.label_6.setText(_translate("Dialog", "Общая площадь, м2"))
        self.label_7.setText(_translate("Dialog", "Норма продолжительности строительства, мес."))
        self.pushButton_2.setText(_translate("Dialog", "Выход"))
        self.pushButton_3.setText(_translate("Dialog", "Интерполяция "))
        self.pushButton_4.setText(_translate("Dialog", "Экстраполяция "))
        self.pushButton_5.setText(_translate("Dialog", "Расчетный метод"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; color:#2d2d2d; background-color:#ffffff;\">Продолжительность строительства объектов, мощность (или другой показатель) которых отличается от приведенных в нормах и находится в интервале между ними, определяется </span><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; text-decoration: underline; color:#2d2d2d; background-color:#ffffff;\">интерполяцией</span><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; color:#2d2d2d; background-color:#ffffff;\">, а за пределами максимальных или минимальных значений норм - </span><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; text-decoration: underline; color:#2d2d2d; background-color:#ffffff;\">экстраполяцией</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; color:#2d2d2d; background-color:#ffffff;\">Продолжительность строительства объектов, не приведенных в таблицах норм, определяется в проектах организации строительства исходя из стоимости строительно-монтажных работ в соответствии с </span><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; text-decoration: underline; color:#2d2d2d; background-color:#ffffff;\">рачетным методом</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial,sans-serif\'; font-size:9pt; color:#2d2d2d;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "Продолжительность строительства, мес."))
        self.label_10.setText(_translate("Dialog", "Количество свай"))
        self.pushButton.setText(_translate("Dialog", "Продолжительность\n"
"строительства \n"
"с учетом свай"))
        self.label_11.setText(_translate("Dialog", "Результат"))
        self.radioButton.setText(_translate("Dialog", "2 секции"))
        self.radioButton_2.setText(_translate("Dialog", "4 секции"))
        self.radioButton_3.setText(_translate("Dialog", "более 4-х секций"))
        self.pushButton_6.setText(_translate("Dialog", "Итоговый расчет"))
        self.label_12.setText(_translate("Dialog", "месяцев"))
