# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(685, 408)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 211, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 651, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 291, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 150, 431, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(504, 370, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 370, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBar.setGeometry(QtCore.QRect(660, 70, 20, 81))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 170, 661, 61))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 59))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(260, 10, 201, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setGeometry(QtCore.QRect(580, 20, 41, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 15, 191, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 20, 31, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(500, 10, 81, 41))
        self.label_6.setObjectName("label_6")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 240, 661, 111))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 659, 109))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 361, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 281, 21))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 70, 231, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 70, 41, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(380, 10, 41, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(290, 40, 41, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 70, 641, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Главная"))
        self.label.setText(_translate("Dialog", "Наименование объекта строительства "))
        self.lineEdit.setText(_translate("Dialog", "Жилой дом 15-этажное двухсекционное здание "))
        self.label_3.setText(_translate("Dialog", "Местонахождение и описание объекта строительства "))
        self.label_4.setText(_translate("Dialog", "Коэффициенты к нормам продолжительности строительства "))
        self.pushButton_3.setText(_translate("Dialog", "Ок"))
        self.pushButton_4.setText(_translate("Dialog", "Отмена "))
        self.pushButton.setText(_translate("Dialog", "Природно-климатические условия"))
        self.lineEdit_5.setText(_translate("Dialog", "1.1"))
        self.label_5.setText(_translate("Dialog", "Природно-климатические условия"))
        self.lineEdit_4.setText(_translate("Dialog", "1.6"))
        self.label_6.setText(_translate("Dialog", "Сейсмичность "))
        self.label_7.setText(_translate("Dialog", "Объект из легких металлических конструкций комплектной поставки"))
        self.label_9.setText(_translate("Dialog", "Объект, сооружаемый комплектно-блочным методом"))
        self.label_8.setText(_translate("Dialog", "Сменность работ "))
        self.pushButton_2.setText(_translate("Dialog", "Технология и организация строительства"))
        self.lineEdit_7.setText(_translate("Dialog", "0.9"))
        self.lineEdit_6.setText(_translate("Dialog", "1.0"))
        self.lineEdit_8.setText(_translate("Dialog", "1.0"))
        self.lineEdit_2.setText(_translate("Dialog", "г. Москва, ул. Летчика Бабушкина, вл. 29 корп.2"))
