# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'technology.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(728, 332)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 16))
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 30, 691, 91))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 371, 16))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 21, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 281, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 40, 21, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(440, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(520, 10, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEnabled(False)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(520, 40, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEnabled(False)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(440, 40, 71, 16))
        self.label_5.setObjectName("label_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 150, 691, 131))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 689, 129))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 81, 16))
        self.label_7.setObjectName("label_7")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 20, 671, 91))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 669, 89))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 461, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_10.setGeometry(QtCore.QRect(30, 50, 141, 16))
        self.label_10.setObjectName("label_10")
        self.radioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 10, 16, 17))
        self.radioButton.setText("1.0")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 30, 20, 20))
        self.radioButton_2.setText("0.9")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 50, 16, 17))
        self.radioButton_3.setText("0.8")
        self.radioButton_3.setObjectName("radioButton_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 300, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 300, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Технология и организация"))
        self.label.setText(_translate("Dialog", "Технология строительства "))
        self.label_2.setText(_translate("Dialog", "объекты из легких металлических конструкций комплектной поставки"))
        self.label_3.setText(_translate("Dialog", "объект, сооружаемый комплектно-блочным методом "))
        self.label_4.setText(_translate("Dialog", "Коэффициент"))
        self.lineEdit.setText(_translate("Dialog", "0.75"))
        self.lineEdit_2.setText(_translate("Dialog", "1.0"))
        self.label_5.setText(_translate("Dialog", "Коэффициент"))
        self.label_7.setText(_translate("Dialog", "Коэффициент:"))
        self.label_8.setText(_translate("Dialog", "1.0 - работа основных строительных машин в 2 смены, остальные работы - в 1,5 смены"))
        self.label_9.setText(_translate("Dialog", "0.9 - все работы в 2 смены"))
        self.label_10.setText(_translate("Dialog", "0.8 - все работы в 3 смены"))
        self.label_6.setText(_translate("Dialog", "Сменность работ"))
        self.pushButton.setText(_translate("Dialog", "ОК"))
        self.pushButton_2.setText(_translate("Dialog", "Отмена"))
